In [41]:
import pandas as pd
import numpy as np

df_before=pd.read_csv('/Users/kimjong-gyu/Desktop/github/3rdBA/3rdBA/BA_TeamProject/before_selection.csv')

In [42]:
df_before.head()

,id,timestamp_first_active,gender,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,first_affiliate_tracked,...,action,action_type,action_detail,device_type,lat_destination,lng_destination,distance_km,destination_km2,destination_language,language_levenshtein_distance
0,4rvqpxoh3h,20140101002619,FEMALE,36.0,basic,25,en,direct,direct,untracked,...,index,-unknown-,-unknown-,iPhone,54.63322,-3.432277,6883.659,243610.0,eng,0.0
1,ccl1h3nes7,20140101184509,MALE,47.0,basic,24,en,direct,direct,linked,...,tos_confirm,-unknown-,-unknown-,-unknown-,54.63322,-3.432277,6883.659,243610.0,eng,0.0
2,0l461nxs9e,20140102003350,FEMALE,22.0,facebook,0,en,sem-brand,google,omg,...,show,view,p3,Mac Desktop,54.63322,-3.432277,6883.659,243610.0,eng,0.0
3,3l77c9axia,20140102221840,FEMALE,85.0,facebook,0,en,direct,direct,omg,...,show,view,p3,Windows Desktop,54.63322,-3.432277,6883.659,243610.0,eng,0.0
4,r6jyrxsb5z,20140103042927,MALE,36.0,basic,0,en,direct,direct,untracked,...,pending,view,-unknown-,Windows Desktop,54.63322,-3.432277,6883.659,243610.0,eng,0.0

In [43]:
df_before.columns

Index(['id', 'timestamp_first_active', 'gender', 'age', 'signup_method',
       'signup_flow', 'language', 'affiliate_channel', 'affiliate_provider',
       'first_affiliate_tracked', 'signup_app', 'first_device_type',
       'first_browser', 'country_destination', 'tfa_date', 'duration',
       'cat_duration', 'action_sum', 'action_count', 'action', 'action_type',
       'action_detail', 'device_type', 'lat_destination', 'lng_destination',
       'distance_km', 'destination_km2', 'destination_language ',
       'language_levenshtein_distance'],
      dtype='object')

In [44]:
df_before=df_before.drop(['action_sum'],axis=1)

In [45]:
# affiliate_channel , affliate_provider , first_affiliate_tracked , signup_app ,first_device_type ,signup_method
# 위에꺼는 초기 접속에 관련된 변수 이기때문에 우리 타켓 벨류는 처음 사용 하고 예약 날짜와의 차이기 때문에 연관성이 없어보인다.
df_before=df_before.drop(['affiliate_channel','affiliate_provider','first_affiliate_tracked','signup_app','first_device_type'],axis=1)

In [46]:
df_before=df_before.drop(['signup_method'],axis=1)

In [47]:
# timestamp_first_active, tfa_date 는 우리 타켓 밸류를 만들기 위해 사용한 함수기 때문에 없앤다.
df_before=df_before.drop(['timestamp_first_active','tfa_date'], axis=1)

In [48]:
df_before.head()

,id,gender,age,signup_flow,language,first_browser,country_destination,duration,cat_duration,action_count,action,action_type,action_detail,device_type,lat_destination,lng_destination,distance_km,destination_km2,destination_language,language_levenshtein_distance
0,4rvqpxoh3h,FEMALE,36.0,25,en,-unknown-,GB,1,VF,8,index,-unknown-,-unknown-,iPhone,54.63322,-3.432277,6883.659,243610.0,eng,0.0
1,ccl1h3nes7,MALE,47.0,24,en,Chrome,GB,82,VS,9,tos_confirm,-unknown-,-unknown-,-unknown-,54.63322,-3.432277,6883.659,243610.0,eng,0.0
2,0l461nxs9e,FEMALE,22.0,0,en,Chrome,GB,11,S,67,show,view,p3,Mac Desktop,54.63322,-3.432277,6883.659,243610.0,eng,0.0
3,3l77c9axia,FEMALE,85.0,0,en,IE,GB,103,VS,42,show,view,p3,Windows Desktop,54.63322,-3.432277,6883.659,243610.0,eng,0.0
4,r6jyrxsb5z,MALE,36.0,0,en,Chrome,GB,0,VF,93,pending,view,-unknown-,Windows Desktop,54.63322,-3.432277,6883.659,243610.0,eng,0.0

In [49]:
df_before.language_levenshtein_distance.describe()

count    25080.000000
mean        13.000973
std         31.437774
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max         95.450000
Name: language_levenshtein_distance, dtype: float64

In [50]:
# language_levenshtein_distance , distance_km , lat_destination , lng_destination , country_destination 
# 위에 변수들은 destination_km가 있으므로 필요가 없고 위도 경도는 단지 그 지역의 위치만 알려주기 때문에 필요가 없다고 판단했다.
df_before=df_before.drop(['language_levenshtein_distance','distance_km','lat_destination','lng_destination','country_destination'], axis=1)

In [51]:
# action_type , action_detail , action 는 action_count를 구하기 위한 변수라 필요 없다고 판단 .
df_before=df_before.drop(['action_type','action_detail','action'],axis=1)

In [52]:
# cat_duration 이 타켓 벨류 
# duration 값이 cat_duration 을 카테고리컬 데이터로 만든거니 필요가 없다고 판단 .
df_before=df_before.drop(['duration'],axis=1)

In [53]:
# dummy 데이터 생성 
df_before.corr()

                      age  signup_flow  action_count  destination_km2
age              1.000000    -0.080338     -0.024123        -0.028171
signup_flow     -0.080338     1.000000      0.062213         0.058266
action_count    -0.024123     0.062213      1.000000        -0.042373
destination_km2 -0.028171     0.058266     -0.042373         1.000000

In [54]:
df_before.head()

,id,gender,age,signup_flow,language,first_browser,cat_duration,action_count,device_type,destination_km2,destination_language
0,4rvqpxoh3h,FEMALE,36.0,25,en,-unknown-,VF,8,iPhone,243610.0,eng
1,ccl1h3nes7,MALE,47.0,24,en,Chrome,VS,9,-unknown-,243610.0,eng
2,0l461nxs9e,FEMALE,22.0,0,en,Chrome,S,67,Mac Desktop,243610.0,eng
3,3l77c9axia,FEMALE,85.0,0,en,IE,VS,42,Windows Desktop,243610.0,eng
4,r6jyrxsb5z,MALE,36.0,0,en,Chrome,VF,93,Windows Desktop,243610.0,eng

In [55]:
df_before=df_before.drop(['language'], axis=1)

In [56]:
df_before.head()

,id,gender,age,signup_flow,first_browser,cat_duration,action_count,device_type,destination_km2,destination_language
0,4rvqpxoh3h,FEMALE,36.0,25,-unknown-,VF,8,iPhone,243610.0,eng
1,ccl1h3nes7,MALE,47.0,24,Chrome,VS,9,-unknown-,243610.0,eng
2,0l461nxs9e,FEMALE,22.0,0,Chrome,S,67,Mac Desktop,243610.0,eng
3,3l77c9axia,FEMALE,85.0,0,IE,VS,42,Windows Desktop,243610.0,eng
4,r6jyrxsb5z,MALE,36.0,0,Chrome,VF,93,Windows Desktop,243610.0,eng

In [38]:
catvar=['gender','first_browser','device_type']
for c in catvar:
    temp=pd.get_dummies(df_before[c],prefix=c, drop_first=True)
    df_before=pd.concat((df_before,temp),axis=1)
    
df_before=df_before.drop(catvar,axis=1)

In [58]:
df_before

,id,gender,age,signup_flow,first_browser,cat_duration,action_count,device_type,destination_km2,destination_language
0,4rvqpxoh3h,FEMALE,36.0,25,-unknown-,VF,8,iPhone,243610.0,eng
1,ccl1h3nes7,MALE,47.0,24,Chrome,VS,9,-unknown-,243610.0,eng
2,0l461nxs9e,FEMALE,22.0,0,Chrome,S,67,Mac Desktop,243610.0,eng
3,3l77c9axia,FEMALE,85.0,0,IE,VS,42,Windows Desktop,243610.0,eng
4,r6jyrxsb5z,MALE,36.0,0,Chrome,VF,93,Windows Desktop,243610.0,eng
...,...,...,...,...,...,...,...,...,...,...
25075,7swui9xebm,FEMALE,21.0,0,Chrome,VF,16,Mac Desktop,92090.0,por
25076,w2dksnar6w,MALE,36.0,0,Safari,VF,43,Mac Desktop,92090.0,por
25077,54rv3t67vr,FEMALE,26.0,0,Chrome,VF,126,Mac Desktop,92090.0,por
25078,kba7p262yt,MALE,19.0,0,IE,VF,356,Tablet,92090.0,por
25079,556jtq4gag,MALE,36.0,0,Firefox,VF,35,Windows Desktop,92090.0,por

In [59]:
df_before.to_csv("/Users/kimjong-gyu/Desktop/github/3rdBA/3rdBA/BA_TeamProject/after_selection.csv", index=False)